
import java.util.HashSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ledes
 */
public class CalculadoraGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PlValores = new javax.swing.JPanel();
        LbRespuesta = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        txtValor1 = new javax.swing.JTextField();
        Valor1lb = new javax.swing.JLabel();
        LbValor2 = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbFaC = new javax.swing.JLabel();
        Valor2txt1 = new javax.swing.JTextField();
        PlOperaciones = new javax.swing.JPanel();
        btbSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlTitulo.setBackground(new java.awt.Color(251, 141, 160));
        PlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calculadora básica");
        PlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 20, 299, 54));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-budget-64.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        PlTitulo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 14, 62, -1));

        getContentPane().add(PlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 80));

        PlValores.setBackground(new java.awt.Color(251, 108, 144));
        PlValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbRespuesta.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        LbRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        LbRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbRespuesta.setText("Respuesta: ");
        PlValores.add(LbRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txtRespuesta.setEditable(false);
        txtRespuesta.setBackground(new java.awt.Color(255, 255, 255));
        txtRespuesta.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuestaActionPerformed(evt);
            }
        });
        PlValores.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 160, 40));

        txtValor1.setBackground(new java.awt.Color(255, 255, 255));
        txtValor1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor1ActionPerformed(evt);
            }
        });
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        PlValores.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 30));

        Valor1lb.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Valor1lb.setForeground(new java.awt.Color(255, 255, 255));
        Valor1lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Valor1lb.setText("Valor 1: ");
        PlValores.add(Valor1lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        LbValor2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        LbValor2.setForeground(new java.awt.Color(255, 255, 255));
        LbValor2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbValor2.setText("Valor 2: ");
        PlValores.add(LbValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 100, 30));

        txtF.setBackground(new java.awt.Color(255, 255, 255));
        txtF.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFActionPerformed(evt);
            }
        });
        txtF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFKeyTyped(evt);
            }
        });
        PlValores.add(txtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, 30));
        PlValores.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        lbFaC.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbFaC.setForeground(new java.awt.Color(255, 255, 255));
        lbFaC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbFaC.setText("Fahrenheit a Celsius:");
        PlValores.add(lbFaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 30));

        Valor2txt1.setBackground(new java.awt.Color(255, 255, 255));
        Valor2txt1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Valor2txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Valor2txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valor2txt1ActionPerformed(evt);
            }
        });
        Valor2txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Valor2txt1KeyTyped(evt);
            }
        });
        PlValores.add(Valor2txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 90, 30));

        getContentPane().add(PlValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 310, 280));

        PlOperaciones.setBackground(new java.awt.Color(251, 192, 192));
        PlOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btbSumar.setText("Sumar");
        btbSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSumarActionPerformed(evt);
            }
        });
        PlOperaciones.add(btbSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 90, 30));

        btnRestar.setText("Restar");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        PlOperaciones.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 90, 30));

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        PlOperaciones.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 90, 30));

        btnDividir.setText("Dividir");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        PlOperaciones.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 90, 30));

        jButton5.setText("Resetear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        PlOperaciones.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, 40));

        jButton7.setText("Convertir a Celcius");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        PlOperaciones.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, 40));

        getContentPane().add(PlOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 440, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFActionPerformed

    private void btbSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSumarActionPerformed
        // llamado de metodos del campo sumar
        ValidarCampos();
        SumarValores();
    }//GEN-LAST:event_btbSumarActionPerformed
    // validando que el btn sumar no reciba info vacia
    private void ValidarCampos() {
         if (txtValor1.getText().trim().length() <= 0) {
             JOptionPane.showMessageDialog(null, "Favor ingresar valor 1 porque el campo esta vacio.");
             txtValor1.requestFocus();
             //Valor2 validacion 
         } else if (txtF.getText().trim().length() <= 0) {
             JOptionPane.showMessageDialog(null, "Favor ingresar valor 2 porque el campo esta vacio.");
             txtF.requestFocus();
     }
    }
    
    //metodo que realiza la operacion sumar 
    private void SumarValores () {
        Calculadora cal = new Calculadora(); 
        Double respuesta = cal.sumar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtF.getText()));
        txtRespuesta.setText(respuesta + "");
    }
    
    //metodo que limpia los campos 
    private void limpiarCampos() {
        txtValor1.setText("");
        txtF.setText("");
        txtRespuesta.setText("");
        txtValor1.requestFocus();
    }
    
    
    
    
    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        // llamada metodos del btn multiplicar 
        ValidarCampos();
        MultiplicarValores();
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void MultiplicarValores() {
        Calculadora cal = new Calculadora(); 
        Double respuesta = cal.multiplicar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtF.getText()));
        txtRespuesta.setText(respuesta + "");
    }
    
    
    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        // llamada de metodos del btb dividir 
        ValidarCampos();
        DividirValores();
    }//GEN-LAST:event_btnDividirActionPerformed

    private void DividirValores() {
    Calculadora cal = new Calculadora();
    Double respuesta = cal.dividir(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtF.getText()));
    txtRespuesta.setText(respuesta + "");
    }
    
    
    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        // validacion de entrada de datos para el campo de txt1

        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor1KeyTyped

    private void txtFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFKeyTyped
        // validacion de entrada de datos para el campo txt2
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "");
            evt.consume();
        }
    }//GEN-LAST:event_txtFKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // llamada a metodos del btn resetear
        
        limpiarCampos(); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        // validamos los campos para la resta 
        
        ValidarCampos();
        RestarValores();
    }//GEN-LAST:event_btnRestarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ValidarCampos();
        ConvertirF();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Valor2txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valor2txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Valor2txt1ActionPerformed

    private void Valor2txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Valor2txt1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Valor2txt1KeyTyped
    
    private void ConvertirF() {
    
    
    Calculadora cal = new Calculadora(); 
    Double respuesta = cal.ConvertirFarenheit(Double.parseDouble(txtF.getText()));
    txtRespuesta.setText(respuesta + "");
        
    }
    
    
    
    
    
    // metodo de restar 
    
    private void RestarValores() {
        Calculadora cal = new Calculadora(); 
        Double respuesta = cal.restar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtF.getText()));
        txtRespuesta.setText(respuesta + "");
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbRespuesta;
    private javax.swing.JLabel LbValor2;
    private javax.swing.JPanel PlOperaciones;
    private javax.swing.JPanel PlTitulo;
    private javax.swing.JPanel PlValores;
    private javax.swing.JLabel Valor1lb;
    private javax.swing.JTextField Valor2txt1;
    private javax.swing.JButton btbSumar;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbFaC;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtValor1;
    // End of variables declaration//GEN-END:variables
}
