/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ledes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PL1 = new javax.swing.JPanel();
        PL2 = new javax.swing.JPanel();
        LB1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LB2 = new javax.swing.JLabel();
        PL3 = new javax.swing.JPanel();
        LB3 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        LB4 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        LB5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PL1.setBackground(new java.awt.Color(255, 255, 255));
        PL1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PL2.setBackground(new java.awt.Color(20, 93, 160));
        PL2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LB1.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        LB1.setForeground(new java.awt.Color(0, 0, 0));
        LB1.setText("Sistema de facturacion");
        PL2.add(LB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 610, 50));

        PL1.add(PL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 664, 64));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PL1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 56, -1, -1));

        LB2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        LB2.setForeground(new java.awt.Color(0, 0, 0));
        LB2.setText("INICIAR SESION ");
        PL1.add(LB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 330, 30));

        PL3.setBackground(new java.awt.Color(12, 45, 72));

        javax.swing.GroupLayout PL3Layout = new javax.swing.GroupLayout(PL3);
        PL3.setLayout(PL3Layout);
        PL3Layout.setHorizontalGroup(
            PL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        PL3Layout.setVerticalGroup(
            PL3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        PL1.add(PL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 60, 110, 360));

        LB3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LB3.setForeground(new java.awt.Color(0, 0, 0));
        LB3.setText("Contraseña:");
        PL1.add(LB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, -1));

        txt2.setBackground(new java.awt.Color(177, 212, 224));
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        PL1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 230, 40));

        LB4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LB4.setForeground(new java.awt.Color(0, 0, 0));
        LB4.setText("Usuario:");
        PL1.add(LB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 110, -1));

        txt1.setBackground(new java.awt.Color(177, 212, 224));
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        PL1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 230, 40));

        btn1.setBackground(new java.awt.Color(46, 139, 192));
        btn1.setForeground(new java.awt.Color(0, 0, 0));
        btn1.setText("Iniciar sesion");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        PL1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 160, 50));

        LB5.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        LB5.setForeground(new java.awt.Color(0, 0, 0));
        LB5.setText("INICIAR SESION ");
        PL1.add(LB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 330, 30));

        getContentPane().add(PL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB1;
    private javax.swing.JLabel LB2;
    private javax.swing.JLabel LB3;
    private javax.swing.JLabel LB4;
    private javax.swing.JLabel LB5;
    private javax.swing.JPanel PL1;
    private javax.swing.JPanel PL2;
    private javax.swing.JPanel PL3;
    private javax.swing.JButton btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
